name: Create Issue on Org Member Add
 
on:
  repository_dispatch:
    types: [triggered-by-org-member-add]
 
jobs:
  create_issue:
    runs-on: ubuntu-latest
 
    steps:
      - name: Write issue content to file
        run: |
          echo "## Summary" > issue-body.md
          echo "${{ github.event.client_payload.issue_summary }}" >> issue-body.md
          echo "" >> issue-body.md
          echo "_This issue was automatically created by a webhook trigger._" >> issue-body.md
      - name: Create an issue from file
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ secrets.TOKEN }}
          title: ${{ github.event.client_payload.issue_title }}
          content-filepath: issue-body.md
          labels: notification
